stages:
  - test

test_script:
  stage: test
  image: python:3.11.8-bookworm
  before_script:
    - apt-get update
    - apt-get install openjdk-17-jdk-headless -y
    - python -m ensurepip
    - python -m pip install --upgrade pip
  script:
    - chmod +x ./generate-data.sh
    - ./generate-data.sh
